# Generated by Django 2.2.5 on 2021-01-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210101_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='checkout_out',
            new_name='check_out',
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
